#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['blinker']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

setup(name='blinker',
      version='1.6.3',
      description='Fast, simple object-to-object and broadcast signaling',
      author=None,
      author_email='Jason Kirtland <jek@discorporate.us>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      python_requires='>=3.7',
     )
